// Autogenerated file run "yarn mk-locales"

export const validTranslationKeys = {
    es: {
        'common:menu.home': 'Dashboard',
        'common:menu.schemas': 'Schemas',
        'common:menu.content': 'Contenidos',
        'common:menu.endpoints': 'Endpoints',
        'common:menu.nodes': 'Nodos',
        'common:menu.uploads': 'Uploads',
        'common:menu.user': 'Usuario',
        'common:menu.logout': 'Cerrar sesión',
        'common:leftPannelTitle.content': 'Archivos',
        'common:leftPannelTitle.schemas': 'Listado',
        'common:leftPannelTitle.endpoints': 'Scripts',
        'common:leftPannelTitle.nodes': 'Inventario',
        'common:leftPannelTitle.user': 'Perfil',
        'common:leftPannelTitle.uploads': 'Media',
        'endpoints:save': 'Guardar',
        'tables:headerTitle.uuid': 'id',
        'tables:headerTitle.name': 'nombre',
        'tables:headerTitle.description': 'descripcion',
        'tables:headerTitle.properties': 'propiedades',
        'tables:headerTitle.timesUsed': 'en uso',
        'tables:headerTitle.lastChange': 'modificado',
        'tables:headerTitle.createdAt': 'creado',
        'tables:headerTitle.changedBy': 'modificado por',
        'tables:headerTitle.createdBy': 'creado por',
        'tables:headerTitle.parent': 'padre',
        'tables:headerTitle.children': 'hijos',
        'tables:headerTitle.locked': 'bloqueado',
    },
}

export type iKeyTranslations =
    | 'common:menu.home'
    | 'common:menu.schemas'
    | 'common:menu.content'
    | 'common:menu.endpoints'
    | 'common:menu.nodes'
    | 'common:menu.uploads'
    | 'common:menu.user'
    | 'common:menu.logout'
    | 'common:leftPannelTitle.content'
    | 'common:leftPannelTitle.schemas'
    | 'common:leftPannelTitle.endpoints'
    | 'common:leftPannelTitle.nodes'
    | 'common:leftPannelTitle.user'
    | 'common:leftPannelTitle.uploads'
    | 'endpoints:save'
    | 'tables:headerTitle.uuid'
    | 'tables:headerTitle.name'
    | 'tables:headerTitle.description'
    | 'tables:headerTitle.properties'
    | 'tables:headerTitle.timesUsed'
    | 'tables:headerTitle.lastChange'
    | 'tables:headerTitle.createdAt'
    | 'tables:headerTitle.changedBy'
    | 'tables:headerTitle.createdBy'
    | 'tables:headerTitle.parent'
    | 'tables:headerTitle.children'
    | 'tables:headerTitle.locked'

export type LangKeys = keyof typeof validTranslationKeys
