// Autogenerated file run "yarn mk-locales"

export const validTranslationKeys = {
    es: {
        'common:menu.home': 'Dashboard',
        'common:menu.schemas': 'Schemas',
        'common:menu.content': 'Contenidos',
        'common:menu.endpoints': 'Endpoints',
        'common:menu.nodes': 'Nodos',
        'common:menu.uploads': 'Uploads',
        'common:menu.user': 'Usuario',
        'common:menu.logout': 'Cerrar sesión',
        'common:leftPannelTitle.content': 'Archivos',
        'common:leftPannelTitle.schemas': 'Listado',
        'common:leftPannelTitle.endpoints': 'Scripts',
        'common:leftPannelTitle.nodes': 'Inventario',
        'common:leftPannelTitle.user': 'Perfil',
        'common:leftPannelTitle.uploads': 'Media',
        'endpoints:save': 'Guardar',
    },
}

export type iKeyTranslations =
    | 'common:menu.home'
    | 'common:menu.schemas'
    | 'common:menu.content'
    | 'common:menu.endpoints'
    | 'common:menu.nodes'
    | 'common:menu.uploads'
    | 'common:menu.user'
    | 'common:menu.logout'
    | 'common:leftPannelTitle.content'
    | 'common:leftPannelTitle.schemas'
    | 'common:leftPannelTitle.endpoints'
    | 'common:leftPannelTitle.nodes'
    | 'common:leftPannelTitle.user'
    | 'common:leftPannelTitle.uploads'
    | 'endpoints:save'

export type LangKeys = keyof typeof validTranslationKeys
